version: "3.8"

services:
  nextjs:
    build: .
    container_name: notlify-admin
    expose:
      - "3005"
    ports:
      - "3005:3005"
    restart: always

  # nginx:
  #   image: nginx:latest
  #   container_name: notlifyNginx
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - nextjs
  #   restart: always
